# Generated by Django 5.1.7 on 2025-03-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cyclone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyclone_id', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=200)),
                ('basin', models.CharField(max_length=200)),
                ('nature', models.CharField(max_length=200)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('dist2land', models.IntegerField()),
                ('storm_dir', models.IntegerField()),
                ('storm_speed', models.IntegerField()),
                ('stage', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
    ]
